name: Maestro Actions Demo
run-name: ${{ github.actor }} is testing out Maestro Actions 🚀
on: [workflow_dispatch]
jobs:
  Run-E2E-Test-on-CI:
    runs-on: "ubuntu-latest"
    name: Run Flow Maestro Cloud
    steps:
      - uses: actions/checkout@v2
      - run: unzip apk/airbnb.apk.zip
      - uses: mobile-dev-inc/action-maestro-cloud@v1.1.0
        with:
            api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
            app-file: airbnb.apk
